import type { AppConfig } from '../../config'
export const featureDefaultConfig: Partial<AppConfig> = {
  show_washer: true,
  show_dryer: true,
  show_dishwasher: true,
  show_ha_sensors: true,
  show_ha_numbers: true,
  show_ha_covers: true,
  show_ha_media: true,
  show_ha_scenes: true,
  show_ha_weather: true,
  mqtt_ha_host: 'HA',
  mqtt_ha_port: 1883,
  mqtt_ha_login: null,
  mqtt_ha_password: null,
  ha_longlived_token: null,
  ha_url: null,
  ha_port: null,
  ha_use_direct_api: false,
  ha_entities: undefined,
  camera_topic: 'kerberos/desktop/events',
  frigate_base_url: null,
  ring_snapshot_url_template: null,
  camera_enabled: true,
}
